export const STOPWORDS = new Set([
  "yang",
  "dan",
  "di",
  "ke",
  "dari",
  "untuk",
  "the",
  "a",
  "an",
  "is",
  "are",
  "i",
  "you",
  "we",
  "they",
  "aku",
  "kamu",
  "saya",
  "ini",
  "itu",
  "with",
  "to",
  "in",
  "on",
  "at",
  "of",
  "it",
  "for",
  "ya",
  "gak",
  "ga",
  "aja",
  "jadi",
  "dan",
  "atau",
  "kok",
  "nih",
  "sih",
  "nih",
]);

export const TOPIC_KEYWORDS: Record<string, string[]> = {
  Programming: ["code", "coding", "bug", "deploy", "api", "javascript", "typescript", "nextjs"],
  Career: ["career", "interview", "cv", "job", "kerja", "gaji", "freelance"],
  Bootcamp: ["bootcamp", "kelas", "training", "course", "belajar"],
  Education: ["study", "campus", "school", "kuliah", "skripsi", "exam"],
  Daily: ["makan", "tidur", "jalan", "rumah", "keluarga", "today", "besok"],
};

export const POSITIVE_WORDS = ["great", "good", "nice", "thanks", "thank", "mantap", "bagus", "keren"];
export const NEGATIVE_WORDS = ["bad", "capek", "lelah", "kesal", "sad", "marah", "sulit", "problem"];
