export const STOPWORDS = new Set([
  "yang",
  "dan",
  "di",
  "ke",
  "dari",
  "untuk",
  "the",
  "a",
  "an",
  "is",
  "are",
  "i",
  "you",
  "we",
  "they",
  "aku",
  "kamu",
  "saya",
  "ini",
  "itu",
  "with",
  "to",
  "in",
  "on",
  "at",
  "of",
  "it",
  "for",
  "ya",
  "gak",
  "ga",
  "aja",
  "jadi",
  "dan",
  "atau",
  "kok",
  "nih",
  "sih",
  "nih",
]);

export const TOPIC_KEYWORDS: Record<string, string[]> = {
  "Ngoding & Produk": [
    "code",
    "coding",
    "bug",
    "deploy",
    "api",
    "javascript",
    "typescript",
    "nextjs",
    "frontend",
    "backend",
    "server",
    "app",
    "fitur",
  ],
  "Kerja & Karier": [
    "career",
    "interview",
    "cv",
    "job",
    "kerja",
    "kantor",
    "gaji",
    "freelance",
    "client",
    "meeting",
    "deadline",
    "promosi",
  ],
  "Belajar & Akademik": [
    "bootcamp",
    "kelas",
    "training",
    "course",
    "belajar",
    "study",
    "campus",
    "school",
    "kuliah",
    "skripsi",
    "exam",
    "ujian",
    "tugas",
  ],
  "Daily Life": ["makan", "tidur", "jalan", "rumah", "keluarga", "today", "besok", "pagi", "malam", "weekend"],
  "Perasaan & Relasi": ["kangen", "sayang", "marah", "maaf", "sorry", "rindu", "cinta", "putus", "baikan", "baper"],
  "Hiburan & Hobi": ["film", "movie", "musik", "lagu", "game", "main", "nonton", "anime", "series", "concert"],
  "Uang & Belanja": ["uang", "duit", "budget", "bayar", "beli", "diskon", "promo", "transfer", "rekening", "invest"],
  "Travel & Nongkrong": ["travel", "trip", "jalan", "liburan", "hotel", "tiket", "nongkrong", "cafe", "kopi", "hangout"],
  "Planning & Keputusan": ["plan", "rencana", "deal", "decide", "jadwal", "setuju", "kesimpulan", "pilih", "booking"],
};

export const POSITIVE_WORDS = ["great", "good", "nice", "thanks", "thank", "mantap", "bagus", "keren"];
export const NEGATIVE_WORDS = ["bad", "capek", "lelah", "kesal", "sad", "marah", "sulit", "problem"];
